version: '3.8'

services:
  db:
    build:
      context: ./server/db
      dockerfile: Dockerfile
    container_name: eventsdb
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  db-data:
